# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://tommichiels.github.io/documentscanning/"

git_url = "https://github.com/tommichiels/documentscanning/tree/master/"

def custom_doc_links(name): return None
